name: CSharpier Check

on:
  pull_request:
    branches:
      - main

jobs:
  csharpier-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "9.0.x"

      - name: Restore tools
        run: dotnet tool restore

      - name: Run CSharpier in check mode
        run: dotnet csharpier . --check
